create database repaso;
use repaso;

grant all privileges on repaso.* to 'repaso'@'%';

CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(128) NOT NULL,
    APELLIDO VARCHAR (128) NOT NULL);

CREATE TABLE TIPOS_CONTACTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(128) NOT NULL);

 CREATE TABLE CONTACTOS (
    -> ID INT PRIMARY KEY AUTO_INCREMENT,
    -> CONTACTO VARCHAR(1024) NOT NULL,
    -> TIPO_CONTACTO_ID INT NOT NULL,
    -> CLIENTE_ID INT NOT NULL,
    -> FOREIGN KEY (TIPO_CONTACTO_ID) REFERENCES TIPOS_CONTACTO(ID),
    -> FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID));